# https://www.sitepoint.com/docker-php-development-environment/

version: "3.8"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped # if you manually stop the stack, it won't restart on reboot (or docker daemon restart)
    tty: true # https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/www # this should be the same for php
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/
    networks:
      - main_network
    depends_on:
      - php
      - mariadb

  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./www:/www # this should be the same for nginx
    networks:
      - main_network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:10.6.2
    restart: unless-stopped
    networks:
      - main_network
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/logs:/var/log/mariadb/
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: db_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.1.1
    networks:
      - main_network
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb

networks:
  main_network:
    name: main_network
    driver: bridge
